### ISSUE TITLE
Build and Release to NPM

### ISSUE THREAD

**Issue by codygulley** [bpmn-io/dmnlint-pack-config#2]
__Is your feature request related to a problem? Please describe__
No released version and thus not available as an [npm](https://www.npmjs.com/) repository.

__Describe the solution you'd like__

Please build a release to npm repository. 

__Describe alternatives you've considered__
N/A

__Additional context__
N/A

**Comment by barmac** [comment]
Released: https://www.npmjs.com/package/dmnlint-pack-config 🎉
